"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.exp = {
    points: ['3', '4', '5', '6', '7', '8', '9', '0', 'J', 'Q', 'K', 'A', '2'],
    joker: 'X',
    jokerRed: 'Y',
    handTypes: {
        ROCKET: 0,
        BOMB: 1,
        SOLO: 2,
        PAIR: 3,
        STRAIGHT: 4,
        CONSECUTIVE_PAIRS: 5,
        TRIO: 6,
        TRIO_SOLO: 7,
        TRIO_PAIR: 8,
        AIRPLANE_SOLO: 10,
        AIRPLANE_PAIR: 11,
        AIRPLANE: 9,
        SPACE_SHUTTLE_SOLO: 12,
        SPACE_SHUTTLE_PAIR: 13,
        FRIED: 14
    },
    handSDTypes: {
        ROCKET: 0,
        BOMB: 1,
        SOLO: 2,
        PAIR: 3,
        STRAIGHT: 4,
        CONSECUTIVE_PAIRS: 5,
        TRIO: 6,
        TRIO_SOLO: 7,
        TRIO_PAIR: 8,
        AIRPLANE_SOLO: 10,
        AIRPLANE_PAIR: 11,
        AIRPLANE: 9,
        SPACE_SHUTTLE_SOLO: 12,
        SPACE_SHUTTLE_PAIR: 13,
        THREE_STRAIGHT: 3,
    },
};
